### PR TITLE
Corrected memory leak in pkcs11_CTX_free v.2

### PR DESCRIPTION
**Pull request by nased0**
It works according to https://github.com/OpenSC/libp11/issues/123#issuecomment-264018817
P.S.
Removed "abominable" and unnecessary conversion :)

### CODE REVIEW

**Comment by mtrojnar** [comment]
Does this PR really fix the memory leak?  It looks fairly harmless...

**Comment by mtrojnar** [comment]
Please squash it into a single commit http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/

**Comment by nased0** [comment]
It only fixes the memory leak (reported by Memory Validator) in data structure sc_pkcs11_module_t that contains the module handle.
It does not free the module. But this is a shared library, so repeated LoadLibrary or dlopen calls on that module should not increase memory usage. 
I would prefer proper finalization and unloading of a module, but it needs to be fixed in OpenSSL itself.
So it is the second best.

**Comment by nased0** [comment]
About rebasing, I'm using only github's www interface, not a git console. And I'm currently at work.

**Comment by mtrojnar** [comment]
Sure.  Take your time.  This is nothing urgent.

**Pull request closed without merging**
