### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/OpenSC/libp11/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/OpenSC/libp11).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by frankmorgner** [comment]
I've browsed through the documentation, but it's unclear to me what lgtm actually does or which metrics is uses. Currently it shows 1 alert: a FIXME. Honestly, this is not what I'd expect from a good code review...

**Comment by xcorail** [comment]
Hi @frankmorgner 
Thanks for this feedback

LGTM runs deep code analysis. Deep as in tackling control flow issues or security vulnerabilities rather than simple style problems. In your case you have only 1 alert because your code is impressively good, as shown by the A+ grades we computed. But if you want to know the kind of problems that our technology is able to find, you can have a look at this [popular project](https://lgtm.com/projects/g/apache/hive/alerts/?mode=tree), or at the security vulnerability that our security team discovered in the [Apple OS Kernel](https://lgtm.com/blog/apple_xnu_icmp_error_CVE-2018-4407).

If you want to actually see LGTM in action on your code, because your current code doesn't show many problems, you can activate automated code review, and try to introduce problems (or wait for one of your contributors to introduce one, assuming they sometimes do). LGTM will analyze your Pull requests, and report any new problem within the comments. It's a [one click operation](https://lgtm.com/projects/g/OpenSC/libp11/ci/) and it's free for public projects. 

Hope I answered your question
Cheers

**Comment by frankmorgner** [comment]
Is there any documentation available about how you're calculating grades or what your *deep code analysis* actually does?

**Comment by xcorail** [comment]
> Is there any documentation available about how you're calculating grades 

You can read about this in this [post](https://lgtm.com/blog/code_quality_1)

> or what your deep code analysis actually does?

Do yo want examples of results for control flow queries? Like [this one](https://lgtm.com/rules/2152620561/alerts/)
Or the exhaustive list of available queries? They are at https://github.com/Semmle/ql
Or do you want to know how we do it and the technology behind? It would be on our [doc](https://lgtm.com/help/lgtm/code-analysis)

Cheers

**Comment by mtrojnar** [comment]
The current output looks pathetic indeed, and I sincerely doubt our code is really so good.
On the other hand the only disadvantage I can see is false sense of security.  Let's give it a try.  Hopefully one day it will prove useful.

**Comment by frankmorgner** [comment]
Then you should add the PR/push trigger for analysis as well!

**Comment by mtrojnar** [comment]
@frankmorgner I'm just a member of the OpenSC organization https://github.com/orgs/OpenSC/people. My privileges are insufficient to enable pull request integration https://lgtm.com/help/lgtm/managing-pr-integration#enabling-pr-integration.  You can enable it as an owner of the OpenSC organization.

**Comment by frankmorgner** [comment]
should work now

**Comment by frankmorgner** [comment]
Is it possible to check online whether those other queries have something useful? I've tried
```
import cpp

select "*"
```
on https://lgtm.com/query/4187256788718604761/ which didn't work...

**Comment by xcorail** [comment]
What were you trying to get exactly with the query above?
You must specify the objects that you want to select
Try for example to get all the functions that are called on your project
```
import cpp
from FunctionCall fc
select fc.getTarget().getName()
```

**Comment by frankmorgner** [comment]
My idea was to get all issues that may not be visible in the "Alerts" tab due to too many false positives.

**Pull request merged**
