### PR TITLE
Add engine ref setup in load_privkey()

### PR DESCRIPTION
**Pull request by mouse07410**
And add the necessary engine set-up in load_privkey()

### CODE REVIEW

**Comment by mtrojnar** [comment]
The title of this PR is confusing...

**Comment by mouse07410** [comment]
OK, hope the new title is better. And the code should speak for itself. ;-)

**Comment by mtrojnar** [comment]
CI testing returns:
```
  CC       pkcs11_la-eng_front.lo
eng_front.c:202:2: error: use of undeclared identifier 'pkey'
        pkey = ctx_load_privkey(ctx, s_key_id, ui_method, callback_data);
        ^
eng_front.c:203:6: error: use of undeclared identifier 'pkey'
        if (pkey)
            ^
eng_front.c:205:3: error: use of undeclared identifier 'pkey'
                pkey->engine = engine;
                ^
eng_front.c:209:9: error: use of undeclared identifier 'pkey'
        return pkey;
               ^
4 errors generated.
```

**Comment by mouse07410** [comment]
Grrr... The complete patch was not done?!

```
diff --git a/src/eng_front.c b/src/eng_front.c
index 9633fe0..6d6638c 100644
--- a/src/eng_front.c
+++ b/src/eng_front.c
@@ -194,12 +194,16 @@ static EVP_PKEY *load_pubkey(ENGINE *engine, const char *s_key_id,
 static EVP_PKEY *load_privkey(ENGINE *engine, const char *s_key_id,
                UI_METHOD *ui_method, void *callback_data)
 {
-       ENGINE_CTX *ctx;
+       ENGINE_CTX *ctx = NULL;
+       EVP_PKEY   *pkey = NULL;
 
        ctx = get_ctx(engine);
        if (ctx == NULL)
                return 0;
-       return ctx_load_privkey(ctx, s_key_id, ui_method, callback_data);
+       pkey = ctx_load_privkey(ctx, s_key_id, ui_method, callback_data);
+       if (pkey)
+  #if OPENSSL_VERSION_NUMBER < 0x10100000L
+               pkey->engine = engine;
+  #else
+  #if defined(EVP_F_EVP_PKEY_SET1_ENGINE)
+               EVP_PKEY_set1_engine(pkey, engine);
+  #endif /* EVP_F_EVP_PKEY_SET1_ENGINE */
+  #endif
+       return pkey;
 }
 
 static int engine_ctrl(ENGINE *engine, int cmd, long i, void *p, void (*f) ())
```

Notice the definition of `pkey` right after `EVP_PKEY_CTX *`.

Added commit. Let me know if you'd rather that I closed this PR and created a new one.

**Comment by mouse07410** [comment]
Thank you!!

**Pull request merged**
