### PR TITLE
Move manual configuration up to the configuration file section and

### PR DESCRIPTION
**Pull request by bmomjian**
update the arguments to match the configuration file example and current
usage.

### CODE REVIEW

**Comment by bmomjian** [comment]
This URL:

   https://github.com/OpenSC/libp11

explains how to configure the OpenSSL config file to know about the libraries under the heading "Using in systems without p11-kit,", but at the bottom it explains that you have to "provide the engine configuration explicitly." I think the second part is unnecessary if the first part is done properly.

**Comment by mtrojnar** [comment]
I agree with adding a clear note that you **either** need to add a configuration file, or commandline options.  Even though this part of the documentation also applies to configuring the engine, I think it fits better in the section on using OpenSSL commandline tools.

**Comment by bmomjian** [comment]
Are you saying this should be moved into the section on the same page titled, "Using the engine from the command line tool", or to some other page?  If so, what other page?

**Comment by mtrojnar** [comment]
same page

**Comment by bmomjian** [comment]
OK, I changed some headings to put it all under "command-line," and adjusted some wording.

**Pull request merged**
