### PR TITLE
Minor modifications to allow compilation under openssl 1.1.0

### PR DESCRIPTION
**Pull request by nmav**
This patch removes warnings and changes calls to conform to 1.1.0b.

### CODE REVIEW

**Comment by nmav** [comment]
(marked as WIP because some issues remain with EC)

**Comment by nmav** [comment]
Test suite seems to work under 1.1.0.

**Comment by mtrojnar** [comment]
Can you explain the reason for removing `ECDSA_SIG_get0()`?

**Comment by mtrojnar** [comment]
One reason could be https://github.com/openssl/openssl/commit/9267c11bb5d408e43482173794f08a3c8472afba I guess...

**Comment by nmav** [comment]
Note that you forgot some fixes such as not including the openssl/dso.h (which isn't exported in 1.1.0)

**Pull request closed without merging**
