### PR TITLE
Add support for Appveyor

### PR DESCRIPTION
**Pull request by vletoux**
add continuous integration for Windows like it is already available for OpenSC

### CODE REVIEW

**Comment by frankmorgner** [comment]
OpenSSL is *not* optional, see https://github.com/OpenSC/engine_pkcs11/pull/32#issuecomment-167223966

**Comment by vletoux** [comment]
I just mimic the OpenSC built process about OpenSSL.
Waiting for a better suggestion ...

**Comment by dengert** [comment]
On 12/25/2015 5:47 AM, vletoux wrote:
    
    
      I just mimic the OpenSC built process about OpenSSL.
        Waiting for a better suggestion ...
    
    
    It is Optional for OpenSC, but required for engine_pkcs11 and
    libp11.
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
Do you know what should be done to make the configure script detect the OpenSSL path on Windows ?
A command line switch or a modification of the configure script ?

**Comment by frankmorgner** [comment]
Try something like `./configure OPENSSL_CFLAGS="-IC:\OpenSSL-Win32\include -IC:\OpenSSL-Win64\include" OPENSSL_LIBS="-LC:\OpenSSL-Win32 -LC:\OpenSSL-Win64 -leay"`. AppVeyor's bash should use mingw by default.

**Comment by vletoux** [comment]
@frankmorgner your suggestion worked. Visual studio is doing the built.
See https://ci.appveyor.com/project/vletoux/libp11 for the build result.

**Comment by frankmorgner** [comment]
looks good now. @nmav , @LudovicRousseau could you have a look?

**Comment by LudovicRousseau** [comment]
I have no objection if it works for you.

**Comment by frankmorgner** [comment]
Hmm, I thought you have the rights to merge this...

One more thing, @vletoux you could add a badge to README.md

**Comment by vletoux** [comment]
I can indeed add a badge, but the badge include the url of the appveyor project.
I can include mine, but given the fact I'm not an owner of OpenSC (nor a contributor), I cannot add the OpenSC repository into Appveyor but only my own fork.
If one of the owner (@LudovicRousseau for example) add the project to Appveyor (for OpenSC it is https://ci.appveyor.com/project/LudovicRousseau) I'll do it.
Same for Engine_pkcs11

**Comment by LudovicRousseau** [comment]
I also added an AppVeyor badge to the Readme.md file

**Comment by vletoux** [comment]
@LudovicRousseau You closed the pull request without merging the changes needed to make appveyor compil with success ...

**Comment by vletoux** [comment]
@LudovicRousseau If I may suggest to add to the appveyor url  of all the readme "/branch/master" to libp11 engine_pkcs11 and OpenSC, you ll get a "nightly build" url.
Example:
https://ci.appveyor.com/project/LudovicRousseau/OpenSC
Become:
https://ci.appveyor.com/project/LudovicRousseau/OpenSC/branch/master

As is, the url leads to all PR builds instead of a latest developer built.

**Comment by LudovicRousseau** [comment]
@vletoux I am not sure to understand what you ask me to do.
If you want to modify the files README.md of the projects then just propose pull requests.

**Pull request merged**
