### PR TITLE
Corrected memory leak in pkcs11_CTX_free(PKCS11_CTX * ctx)

### PR DESCRIPTION
**Pull request by nased0**
I posted the screenshot of the leak at
https://github.com/OpenSC/libp11/issues/122#issuecomment-257850173
Now there are no leaks in pkcs11.dll (tested with Memory Validator and my app utilizing pkcs11 operations via cURL).

### CODE REVIEW

**Comment by mtrojnar** [comment]
Yes, we are aware of this (small) memory leak.  It prevents a deadlock on PKCS#11 modules that internally use the OpenSSL engine interface.
See https://github.com/OpenSC/libp11/issues/123 and https://github.com/OpenSC/libp11/commit/689bd3cc852bcd3e3e1c15f42949a4a577e29dbb for details.

**Comment by nased0** [comment]
I tested my patch a few times with OpenSSL 1.0.2j (compiled by mingw)  and it does not hang on PIN prompt. I have successfully issued commands (on OpenSSL 1.0.2j): https://github.com/OpenSC/libp11/issues/122#issuecomment-262947160 as well as curl commands that ask for PIN:
curl --engine pkcs11 --tlsv1.1 --key-type ENG --cert-type ENG -k https://172.25.223.7:443/cepik/api/skp?wsdl
If my patch hangs the engine on a PIN prompt, please tell me the openssl command that hangs it.
I'm developing a service application, and any memory leaks are unacceptable for me.

**Comment by mtrojnar** [comment]
Simple test cases may not catch this bug.  For example, with OpenSSL < 1.1.0 it requires locking callbacks to be initialized.  Single-threaded applications usually don't initialize locking callbacks.
Also, as I wrote, this bug only emerges with PKCS#11 modules that internally use the OpenSSL engine interface (for example SoftHSM2).

**Comment by nased0** [comment]
Ok. I tested with 
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out c:\tmp\derive.26192.text.sig

engine "pkcs11" set.
PKCS#11 token PIN:

and it hangs after asking for PIN.
But
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:type=private;pin-value=1234" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out c:\tmp\derive.26192.text.sig

engine "pkcs11" set.

It does not ask for PIN and it hangs too!

**Comment by mtrojnar** [comment]
Indeed.  The deadlock has nothing to do with asking for a PIN.

**Comment by nased0** [comment]
I'm not sure that my command is correct, because on unmodified engine it hangs too!
P.S.
I use Encard Enigma card with SSL cert and pkey and USB reader, not SoftHSM2.
I will try to debug it at weekend.

**Comment by nased0** [comment]
I tested this command on openssl 1.0.2j and openssl 1.1.0c:
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:type=private;pin-value=1234" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out c:\tmp\derive.26192.text.sig
again and I realized that it does not hang, but waits for input!
Could you tell me what I'm doing wrong?
P.S.
Command OpenSSL req -engine pkcs11 -new -key "pkcs11:type=private;pin-value=1234"  -keyform engine -out req.pem -text -x509 -subj "/CN=Adam Smith" generates req.pem correctly, so i have no reasons to suspect that -key "pkcs11:type=private;pin-value=1234" is wrong.

**Comment by mtrojnar** [comment]
What does it have to do with the memory leak?

**Comment by nased0** [comment]
I want to verify existence of this deadlock, that prevents us from correcting the memory leak.

**Comment by mtrojnar** [comment]
The proper thread to discuss this issue is #123, and the proper person @mouse07410, who reported it.

**Pull request closed without merging**
