### PR TITLE
Add a minimal test suite

### PR DESCRIPTION
**Pull request by nmav**
That includes a small functionality check.

### CODE REVIEW

**Comment by dwmw2** [comment]
<pre>tests/Makefile.am:11: warning: source file '$(top_srcdir)/examples/auth.c' is in a subdirectory,
tests/Makefile.am:11: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.</pre>

**Comment by nmav** [comment]
That should address it. automake is notorious for asking to add warnings to make things that are supposed to work by default.

**Comment by dengert** [comment]
After running ./bootstrap in the git source, I like to build in a seperate directory from the source (old convention when building for many paltforms from same source. Also makes it easier to clean up):

../../src/configure --prefix=/opt/smartcard 

configure then creates a directore structure and adds VPATH= to Makefiles as needed. 

But the line(11) in tests/Makefile.in:
auth_SOURCES = $(top_srcdir)/examples/auth.c
causes  a director named "$(top_srcdir)" to be created. Output of ls shows: 
./tests:
total 36
-rw-r--r-- 1 doug doug 32608 Jul 13 18:59 Makefile
drwxr-xr-x 3 doug doug  4096 Jul 13 18:59 $(top_srcdir)

./tests/$(top_srcdir):
total 4
drwxr-xr-x 3 doug doug 4096 Jul 13 18:59 examples

./tests/$(top_srcdir)/examples:

Also these lines dont look correct either, as line 5 should have a \

  4 AM_CPPFLAGS = \
  5         -I$(top_srcdir)/
  6         -I$(top_builddir)/

Can you have a look at these issues.
Why did you not just build auth.c in the examples directory?

**Comment by nmav** [comment]
I've just modified it, to address these issues.

**Comment by dengert** [comment]
Still had problems with building auth and using separate build directory. 

It looks like the examples/Makefile.am will try and build all the programs,
but then has problems finding the libp11.h, and -lcrypto.

libp11.h is actually in $(top_srcdir)/src
This may be the only include needed in AM_CPPFLAGS, because ther are no other header files.  

It also looks like the examples/Makefile.am will make sure auth is built.

the examples/Makefile is now generated from Makefile.in and Makefile.am
so should not be copied. 

Please consider adding theses changes. auth, decrypt and getrandom, 
are built  but not installed. Scripts for auth, decrypt and getrandom are in examples and binary files in examples/.libs.


diff --git a/Makefile.am b/Makefile.am
index 5a6c93d..e767874 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -15,7 +15,7 @@ MAINTAINERCLEANFILES = \
 EXTRA_DIST = .gitignore Makefile.mak winconfig.h
 
 dist_noinst_DATA = COPYING bootstrap \
-	$(srcdir)/examples/Makefile $(srcdir)/examples/*.c $(srcdir)/examples/README
+	$(srcdir)/examples/*.c $(srcdir)/examples/README
 dist_doc_DATA = NEWS
 
 SUBDIRS = src doc tests examples
diff --git a/examples/Makefile.am b/examples/Makefile.am
index 32872ab..a943c6d 100644
--- a/examples/Makefile.am
+++ b/examples/Makefile.am
@@ -1,5 +1,9 @@
-AM_CPPFLAGS = -I$(srcdir)
+AM_CFLAGS = $(OPENSSL_CFLAGS)
+AM_CPPFLAGS = \
+	-I$(srcdir) \
+	-I$(top_srcdir)/src \
+	-I$(top_builddir)/
 
 noinst_PROGRAMS = auth decrypt getrandom
 
-LDADD = ../src/libp11.la
+LDADD = ../src/libp11.la  $(OPENSSL_LIBS)
diff --git a/tests/Makefile.am b/tests/Makefile.am
index 376907e..5423e81 100644
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -3,6 +3,7 @@ EXTRA_DIST = cert.der key.der
 AM_CFLAGS = $(OPENSSL_CFLAGS)
 AM_CPPFLAGS = \
 	-I$(top_srcdir)/ \
+	-I$(top_srcdir)/src \
 	-I$(top_builddir)/
 
 AM_LDFLAGS = -no-install

**Comment by dengert** [comment]
There are some "." characters in some of the lines in my last post due to a cut and paste, that should be 
"+" or "-". If needed I can send the file again.

**Comment by nmav** [comment]
> -LDADD = ../src/libp11.la
> +LDADD = ../src/libp11.la  $(OPENSSL_LIBS)

Are you sure you need this part? It is redundant as the .la contains that dependency.

**Comment by dengert** [comment]
It did not link without it on Ubuntu-14.4. That was the last fix I
    added. 
    The programs have calls to OpenSSL routines, that are not used by
    the libp11. 
    Here is part of the make without that $(OPENSSL_LIBS)
    
    Making all in examples
    make[2]: Entering directory
`/afs/anl.gov/appl/OpenSC-dev/build/libp11-git-my/amd64_linux26/examples'
      CC       auth.o
      CCLD     auth
    /usr/bin/ld: auth.o: undefined reference to symbol 'ERR_get_error'
    /opt/smartcard/lib/libcrypto.so.1.0.0: error adding symbols: DSO
    missing from command line
    collect2: error: ld returned 1 exit status
    make[2]: *** [auth] Error 1
    
    I have been using OpenSSL not in a standard location, to test with
    newer OpenSSL versions. 
    OPENSSL_LIBS=-L/opt/smartcard/lib -lcrypto
    OPENSSL_CFLAGS=-I/opt/smartcard/include
    LD_LIBRARY_PATH=/opt/smartcard/lib:
    
    
    On 7/15/2015 1:49 AM, Nikos
      Mavrogiannopoulos wrote:
    
    
      
        -LDADD = ../src/libp11.la
          +LDADD = ../src/libp11.la $(OPENSSL_LIBS)
      
      Are you sure you need this part? It is redundant as the .la
        contains that dependency.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
Then I think that is expected. If you add the "-L/opt/smartcard/lib" in LDFLAGS does it work?

**Comment by nmav** [comment]
That's not black and white, and seems like a pkg-config and libtool issue. I don't pursue it further and simply add the OPENSSL_LIBS in examples.

**Comment by dengert** [comment]
On 7/15/2015 8:24 AM, Nikos
      Mavrogiannopoulos wrote:
    
    
      Then I think that is expected. If you add the
        "-L/opt/smartcard/lib" in LDFLAGS does it work?
    
    Yes, but in OPENSSL_LIBS  I set: 
    OPENSSL_LIBS=-L/opt/smartcard/lib -lcrypto
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
On 7/15/2015 8:29 AM, Nikos
      Mavrogiannopoulos wrote:
    
    
      That's not black and white, and seems like a pkg-config and
        libtool issue. I don't pursue it further and simply add the
        OPENSSL_LIBS in examples.
    
    
    Thanks.
    
     Note The libp11/configure --help    allows them:
      OPENSSL_CFLAGS
                  C compiler flags for OPENSSL, overriding pkg-config
      OPENSSL_LIBS
                  linker flags for OPENSSL, overriding pkg-config
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
And what about the last issue. Can you add in both examples/Makefile.am and tests/Makefile.am 
 -I$(top_srcdir)/src 

This is needed to find the libp11.h when using VPATH builds 

diff --git a/examples/Makefile.am b/examples/Makefile.am
index 32872ab..1b380f1 100644
--- a/examples/Makefile.am
+++ b/examples/Makefile.am
@@ -1,5 +1,9 @@
-AM_CPPFLAGS = -I$(srcdir)
+AM_CFLAGS = $(OPENSSL_CFLAGS)
+AM_CPPFLAGS = \
+       -I$(srcdir) \
+       -I$(top_srcdir)/src \
+       -I$(top_builddir)/
 
 noinst_PROGRAMS = auth decrypt getrandom
 
diff --git a/tests/Makefile.am b/tests/Makefile.am
index 376907e..5423e81 100644
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -3,6 +3,7 @@ EXTRA_DIST = cert.der key.der
 AM_CFLAGS = $(OPENSSL_CFLAGS)
 AM_CPPFLAGS = \
        -I$(top_srcdir)/ \
+       -I$(top_srcdir)/src \
        -I$(top_builddir)/
 
 AM_LDFLAGS = -no-install

**Comment by nmav** [comment]
Fixed and added an additional check.

**Pull request closed without merging**
